name: Deploy to Wow Server

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}

      - name: Deploy on Server
        run: |
          ssh user@$SERVER_IP << 'EOF'
            cd /var/www/html/wow

            # Define all panels and backend
            services=("backend-main" "Driver_Panel" "User_Panel" "admin-panel" "corporate-panel-main" "dispatcher-panel-main" "hotel-panel-main" "hub_panel_main" "partner-panel-main")

            for dir in "${services[@]}"; do
              echo "Processing $dir"
              cd $dir
              git reset --hard origin/main  # Force reset any local changes
              git pull origin main  # Pull latest changes
              npm install --legacy-peer-deps  # Install dependencies
              npm run build-prod  # Build frontend (if applicable)
              cd ..
            done

            # Restart all processes with PM2
            pm2 restart all
          EOF
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
